# Generated by Django 3.2.25 on 2024-04-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20240408_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_feature',
            field=models.ImageField(default='placeholder', upload_to='', verbose_name='image'),
        ),
    ]
